#!/usr/bin/python

from qpid_proton.core import *

container = Container(id="testid")

print("Container ID: {}".format(container.id))

container.connect("localhost")
container.run()

print("The end")
